name: Build and deploy ASP.Net Core app with Angular to Azure Web App - IMSProjectAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Client repository
        uses: actions/checkout@v4
        with:
          repository: devSakaoglu/IMSProject.Client
          path: angular-app  # Specify the path where the Angular code will be cloned
          ref: Publish

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: |
          cd angular-app
          npm install
          ng build --output-path output
          cd ../
        env:
          NG_CLI_ANALYTICS: false


      - name: Checkout backend repository 
        uses: actions/checkout@v4
        with:
          repository: devSakaoglu/IMSProject
          path: backend-app  # Specify the path where the ASP.NET Core code will be cloned


      - name: Copy Angular build to ASP.NET Core project
        run: |
          mkdir -p backend-app/InternshipManagementSystem.API/wwwroot
          cp -r angular-app/output/browser/* backend-app/InternshipManagementSystem.API/wwwroot/

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build backend-app/InternshipManagementSystem.API --configuration Release

      - name: dotnet publish
        run: dotnet publish backend-app/InternshipManagementSystem.API -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IMSProjectAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_109DF26CC4F54DFF92A16B8383D9513F }}
          package: .
